In [1]:
import numpy as np

In [2]:
np.eye(3), np.eye(3,3), np.eye(3, 4), np.eye(3, 4, 1)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [3]:
a = np.diag([1, 2, 3]) 
b = np.arange(9).reshape(3,3)
c = np.diag(b)
d = np.diag([1, 2, 3], 1) 
e = np.diag([1, 2, 3], -1) 

a, b, c, d, e

(array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([0, 4, 8]),
 array([[0, 1, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 3],
        [0, 0, 0, 0]]),
 array([[0, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0]]))

In [4]:
np.vander(np.linspace(0, 2, 5), 4)

array([[0.   , 0.   , 0.   , 1.   ],
       [0.125, 0.25 , 0.5  , 1.   ],
       [1.   , 1.   , 1.   , 1.   ],
       [3.375, 2.25 , 1.5  , 1.   ],
       [8.   , 4.   , 2.   , 1.   ]])

In [5]:
a = np.arange(24).reshape(2, 3, 4)
a, a.shape


(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 (2, 3, 4))

In [6]:
x = np.transpose(a, (2, 1, 0))
x, x.shape


(array([[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],
 
        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],
 
        [[ 2, 14],
         [ 6, 18],
         [10, 22]],
 
        [[ 3, 15],
         [ 7, 19],
         [11, 23]]]),
 (4, 3, 2))

In [7]:
x = np.transpose(a, (1, 2, 0))
x, x.shape


(array([[[ 0, 12],
         [ 1, 13],
         [ 2, 14],
         [ 3, 15]],
 
        [[ 4, 16],
         [ 5, 17],
         [ 6, 18],
         [ 7, 19]],
 
        [[ 8, 20],
         [ 9, 21],
         [10, 22],
         [11, 23]]]),
 (3, 4, 2))