In [16]:
import numpy as np
import sys

##### 基础用法

In [6]:
np.array([2, 3, 4]), np.arange(12).reshape(3, 4)


(array([2, 3, 4]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [5]:
a = np.arange(12, dtype='uint8').reshape(3, 4)
a, a.shape, a.ndim, a.dtype.name, a.itemsize, a.size

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=uint8),
 (3, 4),
 2,
 'uint8',
 1,
 12)

  * zeros, zeros_like
  * ones, ones_like
  * empty, empty_like
  * full, full_like
  * linsapce

In [143]:
a = np.arange(20).reshape(4, 5)

z = np.zeros((3, 4), dtype='uint32')
z1 = np.zeros_like(a)
o = np.ones((3, 4), dtype='uint32')
o1 = np.ones_like(a)
print(z, z1, sep='\n')
print(o, o1, sep='\n')


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [144]:

e = np.empty((3,4), dtype='uint32')
f = np.full((3,4), 255, dtype='uint32')
e1 = np.empty_like(a)
f1 = np.full_like(a, 100)

l = np.linspace(0, 100, 21).astype('uint8')
# np.set_printoptions(threshold=sys.maxsize)
print(e, e1, sep='\n')
print(f, f1, sep='\n')
print(l)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[255 255 255 255]
 [255 255 255 255]
 [255 255 255 255]]
[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [24]:
a = np.arange(1, 6)
a, a**2, a*2, np.sin(a), a == 0, a % 2 == 0

(array([1, 2, 3, 4, 5]),
 array([ 1,  4,  9, 16, 25]),
 array([ 2,  4,  6,  8, 10]),
 array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427]),
 array([False, False, False, False, False]),
 array([False,  True, False,  True, False]))

In [30]:
a = np.arange(1,5)
b = np.arange(2,6)
a, b, a*b, a.dot(b)

(array([1, 2, 3, 4]),
 array([2, 3, 4, 5]),
 array([ 2,  6, 12, 20]),
 40,
 array([2, 3, 4, 5]))

In [ ]:
A = np.array([[1,2,3,4], [2,3,4,5]])
B = np.array([[5,6],[7,8], [5,3],[8,5]])

In [43]:
A, B

(array([[1, 2, 3, 4],
        [2, 3, 4, 5]]),
 array([[5, 6],
        [7, 8],
        [5, 3],
        [8, 5]]))

In [44]:
A.T, B.T

(array([[1, 2],
        [2, 3],
        [3, 4],
        [4, 5]]),
 array([[5, 7, 5, 8],
        [6, 8, 3, 5]]))

In [49]:
A @ B, A.dot(B)

(array([[66, 51],
        [91, 73]]),
 array([[66, 51],
        [91, 73]]))

In [47]:
A * B.T, B * A.T

(array([[ 5, 14, 15, 32],
        [12, 24, 12, 25]]),
 array([[ 5, 12],
        [14, 24],
        [15, 12],
        [32, 25]]))

In [87]:
rg = np.random.default_rng(10)
b = rg.random((3,4),dtype=np.float32)
(b * 20).astype(np.uint8)

array([[15, 19,  5,  4],
       [15, 16, 10,  2],
       [16, 10,  3,  2]], dtype=uint8)

In [88]:
a = np.arange(3)
b = np.exp(a)
c = np.sqrt(a)
a, b, c

(array([0, 1, 2]),
 array([1.        , 2.71828183, 7.3890561 ]),
 array([0.        , 1.        , 1.41421356]))

#### 索引，切片和迭代

In [91]:
a = np.arange(10)**3
print(a, a[1], a[2:5])
a[:6:2] = 1000
print(a)

[  0   1   8  27  64 125 216 343 512 729] 1 [ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]


In [105]:
def fun(x, y):
	return 10*x+y
b = np.fromfunction(fun,(5,4), dtype=np.uint8)
print(b)
print(b[2,3], b[2][3])
print(b[:,2])# 显示第三列
b[:,2] = 10
print(b)
b[::2, ::2] = 20
print(b[::2, ::2])
print(b)
print(b[..., 1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23 23
[ 2 12 22 32 42]
[[ 0  1 10  3]
 [10 11 10 13]
 [20 21 10 23]
 [30 31 10 33]
 [40 41 10 43]]
[[20 20]
 [20 20]
 [20 20]]
[[20  1 20  3]
 [10 11 10 13]
 [20 21 20 23]
 [30 31 10 33]
 [20 41 20 43]]
[ 1 11 21 31 41]


In [137]:
import numpy as np
from PIL import Image

img = np.fromfile('../img.grbg', dtype='uint16').reshape(240, 320)
img = img/4
img = img.astype('uint8')

g1 = img[::2, ::2]
g2 = img[1::2, 1::2]
# g = np.hstack((g1, g2)).reshape(240, 160)
g = np.stack((g1, g2), axis=1).reshape(240, 160)
g = g.repeat(2, axis=1)

r = img[::2, 1::2]
r = r.repeat(2, axis=0).repeat(2, axis=1)

b = img[1::2, ::2]
b = b.repeat(2, axis=0).repeat(2, axis=1)

rgb = np.dstack((r, g, b))

img1 = Image.fromarray(rgb)
img1.save('grbg.jpg')

* floor: 取整数部分
* ceil: 取整数部分+1
* round: 四舍五入 

In [146]:
a = np.array([1.3, 4.3, 6.5, 4.3, 6.7])
b = np.floor(a)
c = np.ceil(a)
d = np.round(a)
b, c, d


(array([1., 4., 6., 4., 6.]),
 array([2., 5., 7., 5., 7.]),
 array([1., 4., 6., 4., 7.]))

两者的功能是一致的，将多维数组降为一维，但是两者的区别是返回拷贝还是返回视图  
`np.flatten()`返回一份拷贝，对拷贝所做修改不会影响原始矩阵，而  
`np.ravel()`返回的是视图，修改时会影响原始矩阵

In [148]:
a = np.arange(12).reshape(3,4)
print(a)
b = a.reshape(6, -1)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
