#### numpy的合并方法
![](axis.png)

In [1]:
import numpy as np
# from pprint import pprint as print
a = np.arange(12).reshape(3,4)
b = np.arange(1, 24, 2).reshape(3,4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


##### numpy stack
```python
stack(arrays, axis=0, out=None) 
```
沿着指定的axis对arrays(每个array的shape必须一样)进行拼接，返回值的维度比原arrays的维度高1  
axis：默认为0，即第一个轴，若为-1即为第二个轴  
![](stack.png)

In [2]:
# 按行合并，如(3,4) (3,4) ==> (2,3,4)
s1 = np.stack((a,b))
print(s1, s1.shape)
print(s1.reshape(6,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]]] (2, 3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [3]:
# 按列合并，如(3,4) (3,4) ==> (3,2,4)
s2 = np.stack((a,b), axis=1)
print(s2, s2.shape)
print(s2.reshape(6,4))

[[[ 0  1  2  3]
  [ 1  3  5  7]]

 [[ 4  5  6  7]
  [ 9 11 13 15]]

 [[ 8  9 10 11]
  [17 19 21 23]]] (3, 2, 4)
[[ 0  1  2  3]
 [ 1  3  5  7]
 [ 4  5  6  7]
 [ 9 11 13 15]
 [ 8  9 10 11]
 [17 19 21 23]]


In [4]:
# 按列合并，如(3,4) (3,4) ==> (3,4,2)
s2 = np.stack((a,b), axis=2)
print(s2, s2.shape)
print(s2.reshape(6,4))

[[[ 0  1]
  [ 1  3]
  [ 2  5]
  [ 3  7]]

 [[ 4  9]
  [ 5 11]
  [ 6 13]
  [ 7 15]]

 [[ 8 17]
  [ 9 19]
  [10 21]
  [11 23]]] (3, 4, 2)
[[ 0  1  1  3]
 [ 2  5  3  7]
 [ 4  9  5 11]
 [ 6 13  7 15]
 [ 8 17  9 19]
 [10 21 11 23]]


In [5]:
# 水平方向 (3, 4) (3, 4) ==> (3, 8)
s3 = np.hstack((a, b))
print(s3, s3.shape)
s31 = np.concatenate((a, b), axis=1)
print(s31, s31.shape)
s32 = np.column_stack((a,b))
print(s32, s32.shape)


[[ 0  1  2  3  1  3  5  7]
 [ 4  5  6  7  9 11 13 15]
 [ 8  9 10 11 17 19 21 23]] (3, 8)
[[ 0  1  2  3  1  3  5  7]
 [ 4  5  6  7  9 11 13 15]
 [ 8  9 10 11 17 19 21 23]] (3, 8)
[[ 0  1  2  3  1  3  5  7]
 [ 4  5  6  7  9 11 13 15]
 [ 8  9 10 11 17 19 21 23]] (3, 8)


In [6]:
#垂直方向 (3, 4) (3, 4) ==> (6, 4)
s4 = np.vstack((a,b))
print(s4, s4.shape)
s41 = np.concatenate((a, b), axis=0)
print(s41, s41.shape)
s42 = np.row_stack((a,b))
print(s42, s42.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]] (6, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]] (6, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]] (6, 4)


#### 深度组合：沿着纵轴方向组合

In [7]:
#沿着纵轴方向 (3, 4) (3, 4) ==> (3, 4, 2), 等同于np.stack((a,b), axis=2)
s1 = np.dstack((a, b))
print(s1, s1.shape)

[[[ 0  1]
  [ 1  3]
  [ 2  5]
  [ 3  7]]

 [[ 4  9]
  [ 5 11]
  [ 6 13]
  [ 7 15]]

 [[ 8 17]
  [ 9 19]
  [10 21]
  [11 23]]] (3, 4, 2)


In [8]:
# np.append([1, 2, 3], [4, 5, 6], [7, 8, 9])
n1 = np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
print(n1)
n2 = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)
print(n2)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
s = np.array([2, 3, 4, 5])
y = np.array([1, 3, 7, 9])
print(np.r_[s, 0, 1, 2, y])
print(np.c_[s, y])
print(np.r_[a, b])
print(np.c_[a, b])


[2 3 4 5 0 1 2 1 3 7 9]
[[2 1]
 [3 3]
 [4 7]
 [5 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
[[ 0  1  2  3  1  3  5  7]
 [ 4  5  6  7  9 11 13 15]
 [ 8  9 10 11 17 19 21 23]]
